### ISSUE TITLE
input datasets

### ISSUE THREAD

**Issue by jinalee-mech** [shiftlab-nanodrone/sparse-gslam#1]
Hello.
I'm wondering what's the input dataset meaning. 
I know input dataset called Radish, but I'm not sure about the exact form of it.
Is it 6Dof Pose and point cloud x, y?

**Comment by hanzhi713** [comment]
We have a number of log parser in this file: https://github.com/shiftlab-nanodrone/sparse-gslam/blob/master/src/sparse_gslam/src/data_provider.cpp

We mostly use the old carmen log format (https://carmen.sourceforge.net/logger_playback.html), and we only use the FLASER entries in the log. This format is mostly what the slam benchmark website provides: http://ais.informatik.uni-freiburg.de/slamevaluation/datasets.php.

**Comment by jinalee-mech** [comment]
Thank you!
