### ISSUE TITLE
roslaunch error

### ISSUE THREAD

**Issue by jinalee-mech** [shiftlab-nanodrone/sparse-gslam#2]
Hello, I just finished installing all required pakages (libg2o and cartographer) except metricEvaluator because I couldn't find that repository link during running ./download.sh. 

After I running `roslaunch sparse_gslam log_runner.launch dataset:={dataset_name}` , I got error and those kinds of results.
![image](https://user-images.githubusercontent.com/90688988/218246270-c59b5e88-da33-489b-a617-b44fa27a9121.png)
![image](https://user-images.githubusercontent.com/90688988/218246290-2dc2a3c3-a4ee-44b4-b18b-02c503cba771.png)
![image](https://user-images.githubusercontent.com/90688988/218246303-0c114a44-3e0c-47c1-bf14-1624d60d8ffd.png)
I think it stopped in the middle of building a map.

Can you help me about this error?
My computer is Ubuntu 18.04 with ROS Melodic.

**Comment by jinalee-mech** [comment]
I think it's because of the libg2o I installed. 
I tried to install with repository you recommended, but I got this error while `catkin_make -DCMAKE_BUILD_TYPE=Release`.
![image](https://user-images.githubusercontent.com/90688988/218691147-e949c09b-da99-4903-bfa9-4fd5de2e4f95.png)

**Comment by hanzhi713** [comment]
> I think it's because of the libg2o I installed. I tried to install with repository you recommended, but I got this error while `catkin_make -DCMAKE_BUILD_TYPE=Release`. ![image](https://user-images.githubusercontent.com/90688988/218691147-e949c09b-da99-4903-bfa9-4fd5de2e4f95.png)

Try running `sudo ldconfig` and then rerun cmake?

If it doesn't work, check the location of installation of g2o or modify FindG2O.cmake (https://github.com/shiftlab-nanodrone/sparse-gslam/blob/master/src/sparse_gslam/cmake/FindG2O.cmake) or do both

Another way is to switch to ubuntu 20.04 with ros noetic, which is the platform I'm using.

**Comment by jinalee-mech** [comment]
I solved it with` sudo make install ` instead of `sudo ldconfig`!
Thanks

**Comment by csd-sudo** [comment]
Hello, could you please tell me how you solved this problem? I am facing the same issue.
