### ISSUE TITLE
CMake Error: The following variables are used in this project, but they are set to NOTFOUND

### ISSUE THREAD

**Issue by ugrm** [shiftlab-nanodrone/sparse-gslam#7]
![image](https://github.com/shiftlab-nanodrone/sparse-gslam/assets/145661518/8f030dad-5785-4b57-addc-a6f88d4cc371)
![image](https://github.com/shiftlab-nanodrone/sparse-gslam/assets/145661518/1ca8dc51-55e4-418b-bd77-760e8132ef9b)
![image](https://github.com/shiftlab-nanodrone/sparse-gslam/assets/145661518/0c7341c0-ff34-4a38-8614-dcdc87c60caa)

I got this error. Any help would be appreciated.

**Comment by hanzhi713** [comment]
Did you build and install g2o according to the readme?

**Comment by ugrm** [comment]
Yeah, but could you take a look at the steps just in case? 

- Downloaded https://github.com/RainerKuemmerle/g2o?tab=readme-ov-file (20200410_git version) and downloaded https://github.com/ros-gbp/libg2o-release
- The first folder was unpacked inside catkin_ws/src and the second folder was unpacked inside catkin_ws
- Did not change anything in config.h.in file 
![image](https://github.com/shiftlab-nanodrone/sparse-gslam/assets/145661518/aca0cbb1-2cc8-4539-8ead-0af8203170ee)

- Changed OFF->ON 
![image](https://github.com/shiftlab-nanodrone/sparse-gslam/assets/145661518/de7fab25-544e-4d1e-ba33-502d6dee1bc3)

- Ran sudo apt install libeigen3-dev libspdlog-dev libsuitesparse-dev qtdeclarative5-dev qt5-qmake libqglviewer-dev-qt5 in terminal (steps from https://github.com/RainerKuemmerle/g2o)
- Compiled using the following commands 
mkdir build
cd build
cmake ../
make
inside catkin_ws/src/g2o-20200410_git

- Ran sudo ldconfig

If there's anything that went wrong please let me know

**Comment by hanzhi713** [comment]
you need to run `sudo make install` after make

**Comment by csd-sudo** [comment]
Hello, could you please tell me how you solved this problem? I am facing the same issue.

**Comment by hanzhi713** [comment]
@csd-sudo Doesn't the solution above help?
