### ISSUE TITLE
Fatal error: cartographer/common/port.h

### ISSUE THREAD

**Issue by ugrm** [shiftlab-nanodrone/sparse-gslam#8]
`catkin_make_isolated -DCMAKE_BUILD_TYPE=Release` gives this error

![image](https://github.com/shiftlab-nanodrone/sparse-gslam/assets/145661518/b2c4aab2-2db3-45a0-b1b8-8d27be7d4859)

Failed to process package 'sparse_gslam'

**Comment by ugrm** [comment]
The only thing that did not work up to this point is uninstalling the ROS abseil-cpp step for building cartographer.  (https://google-cartographer-ros.readthedocs.io/en/latest/compilation.html)
![image](https://github.com/shiftlab-nanodrone/sparse-gslam/assets/145661518/3342f1e4-d3ad-495b-a16b-4570f424b733)

This step gives me this result

![image](https://github.com/shiftlab-nanodrone/sparse-gslam/assets/145661518/91a05149-391f-4016-a9d1-29799bc1348d)

**Comment by hanzhi713** [comment]
If the package isn't installed you can just skip this step

**Comment by ugrm** [comment]
I thought so too but the error regarding port.h keeps coming up. Did you face this problem by any chance?
![image](https://github.com/shiftlab-nanodrone/sparse-gslam/assets/145661518/fc38d8b3-88f0-49bb-a583-07ed0fab4728)
This problem

**Comment by hanzhi713** [comment]
Not quite sure the reason. Did you install cartographer correctly? (i.e. `sudo ninja install`)

**Comment by ugrm** [comment]
yep. still doesn't work. I'll ask my friend though and let you know if it gets fixed. Thanks

**Comment by ugrm** [comment]
Hiya, I still couldn't solve it. Since you mentioned installing the cartographer, I guess it's worth looking at the installation process.
I'm using ubuntu 20.04 and ros noetic. I followed these instructions (https://google-cartographer-ros.readthedocs.io/en/latest/compilation.html). 
I didn't add any extra commands and the only thing I did differently was removing `<depend>libabsl-dev</depend>` from the package.xml file in catkin_ws/src/cartographer.
Are there any hidden(?) steps? Because other than the fatal error, everything until the last roslaunch works perfectly.

**Comment by ugrm** [comment]
And just to clarify, I a catkin_ws for the cartographer (cartographer + cartographer_ros is inside catkin_ws/src) and put libg2o inside catkin_ws, g2o inside catkin_ws/src, and sparse-gslam inside catkin_ws/src.

**Comment by ugrm** [comment]
Add
`include_directories(/home/jeahn/catkin_ws/src/cartographer)`
`include_directories(/home/jeahn/catkin_ws/install_isolated/include)`
to CMakeLists.txt in `~/catkin_ws/src/sparse-gslam/src/sparse_gslam` around line 145~150 so that it comes after include_directories(include....)
